name: Go

on:
  push:
    branches: [main, develop]
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Build, Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Lint
        #uses: golangci/golangci-lint-action@v2
        run: golangci-lint run -v --fix --timeout 5m
        working-directory: ./backend

      - name: Build
        run: go build -v

      - name: Test
        run: go test -race -cover -covermode=atomic -v ./...
